import{a as v,S as R,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const B="30108062-264069135fbcff220b3f8c28b",w="https://pixabay.com/api/",E=15;function g(e,t){const n={key:B,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:E};return v.get(w,{params:n})}function h({downloads:e,comments:t,views:n,likes:o,tags:r,webformatURL:s,largeImageURL:l}){return`
  <li class="gallery-card">
    <a class="gallery-item" href="${l}">
      <img src="${s}" alt="${r}" loading="lazy" class="gallery-image" />
    </a>
    <div class="info">
      <p class="info-item"><b>Likes</b> <span>${o}</span></p>
      <p class="info-item"><b>Views</b> <span>${n}</span></p>
      <p class="info-item"><b>Comments</b> <span>${t}</span></p>
      <p class="info-item"><b>Downloads</b> <span>${e}</span></p>
    </div>
  </li>
`}let f=null;function y(){f?f.refresh():f=new R(".js-gallery a.gallery-item",{captionsData:"alt",captionDelay:250})}function S(e,t){return t!=null&&t.length?(e.innerHTML=t.map(h).join(""),y(),!0):(e.innerHTML="",!1)}function b(){const e=document.getElementById("loader");e&&e.classList.remove("is-hidden")}function L(){const e=document.getElementById("loader");e&&e.classList.add("is-hidden")}function P(e,t){if(!(t!=null&&t.length))return;const n=t.map(h).join("");e.insertAdjacentHTML("beforeend",n),y()}function x(){i.loadBtm&&i.loadBtm.classList.remove("is-hidden")}function p(){i.loadBtm&&i.loadBtm.classList.add("is-hidden")}const i={searchForm:document.querySelector("form.form"),queryInput:document.querySelector('form.form [name="query"]'),gallery:document.querySelector(".js-gallery"),loadBtm:document.querySelector(".load-btm")};i.searchForm.addEventListener("submit",A);i.loadBtm.addEventListener("click",q);let u=1,d="",c=0,m=0;async function A(e){e.preventDefault();const{target:t}=e,n=t.elements.query.value.trim();if(n.length===0){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}d=n,u=1,c=0,m=0,i.gallery.innerHTML="",b(),p();try{const{data:o}=await g(d,u);if(m=o.totalHits??0,!S(i.gallery,o.hits)){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}c=o.hits.length,c<m?x():p()}catch(o){o.status===404||o.status==="404"?a.error({title:"❌ 404 Not Found",message:"The requested resource was not found or does not exist.",position:"topRight"}):a.error({title:"⚠️ Request Error",message:(o==null?void 0:o.message)||"A network or unexpected error occurred.",position:"topRight"})}finally{L()}}async function q(){if(d){u++,b();try{const{data:e}=await g(d,u);P(i.gallery,e.hits),c+=e.hits.length,(c>=e.totalHits||e.hits.length===0)&&(p(),i.loadBtm.removeEventListener("click",q),a.info({title:"End of Results",message:"We're sorry, but you've reached the end of the search results.",position:"topRight"}))}catch(e){a.error({title:"⚠️ Request Error",message:(e==null?void 0:e.message)||"A network or unexpected error occurred.",position:"topRight"})}finally{L()}}}
//# sourceMappingURL=index.js.map
