import{S as c,i as a}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function e(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();const u="30108062-264069135fbcff220b3f8c28b",f="https://pixabay.com/api/";function m(r){const o=new URLSearchParams({key:u,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"}),s=`${f}?${o.toString()}`;return fetch(s).then(e=>{if(!e.ok){const t=new Error(`HTTP ${e.status}`);throw t.status=e.status,t}return e.json()}).then(e=>e.hits).catch(e=>{throw console.error("❌ Fetch error:",e),e})}function p({downloads:r,comments:o,views:s,likes:e,tags:t,webformatURL:n,largeImageURL:i}){return`
  <li class="gallery-card">
    <a class="gallery-item" href="${i}">
      <img src="${n}" alt="${t}" loading="lazy" class="gallery-image" />
    </a>
    <div class="info">
      <p class="info-item"><b>Likes</b> <span>${e}</span></p>
      <p class="info-item"><b>Views</b> <span>${s}</span></p>
      <p class="info-item"><b>Comments</b> <span>${o}</span></p>
      <p class="info-item"><b>Downloads</b> <span>${r}</span></p>
    </div>
  </li>
`}function d(r,o){if(!(o!=null&&o.length)){iziToast.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),r.innerHTML="";return}r.innerHTML=o.map(p).join(""),new c(".js-gallery .gallery-item",{captionsData:"alt",captionDelay:250}).refresh()}function g(){const r=document.getElementById("loader");r&&r.classList.remove("is-hidden")}function y(){const r=document.getElementById("loader");r&&r.classList.add("is-hidden")}const l={searchForm:document.querySelector("form.form"),queryInput:document.querySelector('form.form [name="query"]'),gallery:document.querySelector(".js-gallery")};l.searchForm.addEventListener("submit",h);function h(r){r.preventDefault();const{target:o}=r,s=o.elements.query.value.trim();if(s.length===0){a.warning({title:"Увага",message:"Введи пошуковий запит"});return}l.gallery.innerHTML="",g(),m(s).then(e=>{d(l.gallery,e)}).catch(e=>{e.status===404||e.status==="404"?a.error({title:"❌ 404 Not Found",message:"Ресурс не знайдено або не існує.",position:"topRight"}):a.error({title:"⚠️ Помилка запиту",message:(e==null?void 0:e.message)||"Виникла мережева або інша помилка.",position:"topRight"})}).finally(()=>y())}
//# sourceMappingURL=index.js.map
