import{a as B,S as R,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function i(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=i(r);fetch(r.href,s)}})();const E="30108062-264069135fbcff220b3f8c28b",q="https://pixabay.com/api/",w=15;function h(e,t){const i={key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:w};return B.get(q,{params:i})}function y({downloads:e,comments:t,views:i,likes:o,tags:r,webformatURL:s,largeImageURL:l}){return`
  <li class="gallery-card">
    <a class="gallery-item" href="${l}">
      <img src="${s}" alt="${r}" loading="lazy" class="gallery-image" />
    </a>
    <div class="info">
      <p class="info-item"><b>Likes</b> <span>${o}</span></p>
      <p class="info-item"><b>Views</b> <span>${i}</span></p>
      <p class="info-item"><b>Comments</b> <span>${t}</span></p>
      <p class="info-item"><b>Downloads</b> <span>${e}</span></p>
    </div>
  </li>
`}let f=null;function L(){f?f.refresh():f=new R(".js-gallery a.gallery-item",{captionsData:"alt",captionDelay:250})}function P(e,t){return t!=null&&t.length?(e.innerHTML=t.map(y).join(""),L(),!0):(e.innerHTML="",!1)}function b(){const e=document.getElementById("loader");e&&e.classList.remove("is-hidden")}function v(){const e=document.getElementById("loader");e&&e.classList.add("is-hidden")}function S(e,t){if(!(t!=null&&t.length))return;const i=t.map(y).join("");e.insertAdjacentHTML("beforeend",i),L()}const n={searchForm:document.querySelector("form.form"),gallery:document.querySelector(".js-gallery"),loadBtm:document.querySelector(".load-btm")};function x(){n.loadBtm&&n.loadBtm.classList.remove("is-hidden")}function p(){n.loadBtm&&n.loadBtm.classList.add("is-hidden")}n.searchForm.addEventListener("submit",A);let u=1,d="",c=0,m=0;async function A(e){e.preventDefault(),n.loadBtm.removeEventListener("click",g),n.loadBtm.addEventListener("click",g);const{target:t}=e,i=t.elements.query.value.trim();if(i.length===0){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}d=i,u=1,c=0,m=0,n.gallery.innerHTML="",b(),p();try{const{data:o}=await h(d,u);if(m=o.totalHits??0,!P(n.gallery,o.hits)){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}c=o.hits.length,c<m?x():p()}catch(o){o.response.status===404||o.response.status==="404"?a.error({title:"❌ 404 Not Found",message:"The requested resource was not found or does not exist.",position:"topRight"}):a.error({title:"⚠️ Request Error",message:(o==null?void 0:o.message)||"A network or unexpected error occurred.",position:"topRight"})}finally{v()}}async function g(){if(d){u++,b();try{const{data:e}=await h(d,u);S(n.gallery,e.hits),c+=e.hits.length,(c>=e.totalHits||e.hits.length===0)&&(p(),n.loadBtm.removeEventListener("click",g),a.info({title:"End of Results",message:"We're sorry, but you've reached the end of the search results.",position:"topRight"}))}catch(e){a.error({title:"⚠️ Request Error",message:(e==null?void 0:e.message)||"A network or unexpected error occurred.",position:"topRight"})}finally{v()}}}
//# sourceMappingURL=index.js.map
